alumni/urls.py
from django.urls import path
from . import views

app_name = 'alumni'
urlpatterns = [
  path('', views.alumni_list, name='alumni_list'),
  path('new/', views.alumni_create, name='alumni_create'),
]

anonymous/urls.py
from django.urls import path, include
from . import views

app_name = 'anonymous'
urlpatterns = [
  path('report/', views.submit_report, name='report'),
  path('reports/', views.list_report, name='reports')
]

awards/urls.py
from django.urls import path
from . import views
app_name = 'awards'
urlpatterns =  [
  path('', views.awards, name='awards')
]

blog/urls.py
from django.urls import path
from . import views


app_name = 'blog'
urlpatterns = [
  path('', views.list_post, name='list_post'),
  path('createpost/', views.create_post, name='post_new'),
  path('<int:pk>/editpost/', views.edit_post, name='editpost'),
  path('<int:pk>/', views.detail_post, name='detail_post'),
]

counselor/urls.py
from django.urls import path
from . import views
app_name = 'counselor'
urlpatterns = [
  path('', views.users_view, name='friends'),
  path('<slug:receiver>/', views.chat_view, name='chat'),
  path('post/<slug:receiver>/', views.post, name='post')
]

evoting/urls.py
from django.urls import path
from . import views

app_name = 'evoting'
urlpatterns = [
  path('poll/', views.poll_list, name='polllist'),
  path('poll/<int:pk>/', views.poll_view, name='pollview'),
  path('polls/', views.polls_all, name='polls_all')
]

smartschool/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('anonymous/', include('anonymous.urls', namespace='anonymous')),
    path('blog/', include('blog.urls')),
    path('awards/', include('awards.urls')),
    path('alumni/', include('alumni.urls')),
    path('evoting/', include('evoting.urls')),
    path('counselor/', include('counselor.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

awards/models.py
from django.db import models

# Create your models here.
class Award(models.Model):
  CATEGORY_CHOICES = (
    ('jss1', 'JSS1'),    
    ('jss2', 'JSS2'),   
    ('jss3', 'JSS3'),  
    ('ss1', 'SS1'),
    ('ss2', 'SS2'),
    ('ss3', 'SS3'),
    ('teachers', 'Teachers'),
    ('staff', 'Staff')
  )
  award = models.CharField(max_length=30)
  name = models.CharField(max_length=30)
  category = models.CharField(max_length=30, choices=CATEGORY_CHOICES)
  image = models.ImageField(upload_to='award_pics', default='01.jpg')

awards/views.py
from django.shortcuts import render
from .models import Award

# Create your views here.
def awards(request):
  awards1 = Award.objects.filter(category='jss1')
  awards2 = Award.objects.filter(category='jss2')
  awards3 = Award.objects.filter(category='jss3')
  awards4 = Award.objects.filter(category='ss1')
  awards5 = Award.objects.filter(category='ss2')
  awards6 = Award.objects.filter(category='ss3')
  awards7 = Award.objects.filter(category='teachers')
  awards8 = Award.objects.filter(category='staff')

  return render(request, 'awards/awards.html', {
    'awards1': awards1,
    'awards2': awards2,
    'awards3': awards3,
    'awards4': awards4,
    'awards5': awards5,
    'awards6': awards6,
    'awards7': awards7,
    'awards8': awards8,
  })

awards/templates/awards_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}" media="screen,projection" />
    <link rel="stylesheet" href='{% static "css/style.css" %}'>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav class="teal white-text">
    <div class="container">
      <div class="nav-wrapper">
        <a href="#home" class="brand-logo">MASU SCHOOLS</a>
        <a href="#" class="button-collapse" data-activates="mobile-nav"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down teal-text">
          <li><a href="/" class="m-active-link dropdown-button" data-activates="home">Home</a></li>
          <li><a href="#" class="dropdown-button" data-activates="schools">Schools</a></li>
          <li><a href="#" class="dropdown-button" data-activates="student">Student Corner</a></li>
          <li><a href="#" class="dropdown-button" data-activates="campus">Campus Life</a></li>
          <li><a href="#" class="dropdown-button" data-activates="mss">MSS</a></li>
          <li><a href="#login-modal" class="btn white teal-text modal-trigger">Login</a></li>
          <li><a href="#"><i class="fab fa-facebook"></i> </a></li>
          <li><a href="#"><i class="fab fa-twitter"></i> </a></li>
          <li><a href="#"><i class="fab fa-instagram"></i> </a></li>
          </ul>
          <ul class="side-nav" id="mobile-nav">
              <li><h4 class="teal-text center">MASU SCHOOLS</h4></li>
              <li><div class="divider"></div></li>
              <li><a href="/">Home</a></li>
              <li><a href="#" class="dropdown-button" data-activates="schools-m">Schools</a></li>
              <li><a href="#" class="dropdown-button" data-activates="student-m">Student Corner</a></li>
              <li><a href="#" class="dropdown-button" data-activates="mss-m">MSS</a></li>
              <li><a href="#" class="dropdown-button" data-activates="campus-m">Campus Life</a></li><li><a href="#" class="btn teal">Login</a></li>
              <li><a href="#"><i class="fab fa-facebook"></i> </a></li>
              <li><a href="#"><i class="fab fa-twitter"></i> </a></li>
              <li><a href="#"><i class="fab fa-instagram"></i> </a></li>
          </ul>
      </div>
    </div>

    <!-- Dropdowns -->
    <ul class="dropdown-content" id="schools">
        <li><a href="#">Nursery School</a></li>
        <li><a href="#">Primary School</a></li>
        <li><a href="#">Secondary School</a></li>
    </ul>
    <ul class="dropdown-content" id="home">
        <li><a href="#">About Us</a></li>
        <li><a href="#">History</a></li>
    </ul>
    <ul class="dropdown-content" id="student">
        <li><a href="{% url 'awards:awards' %}">Awards</a></li>
        <li><a href="{% url  'blog:list_post' %}">Blog</a></li>
        <li><a href="{% url 'alumni:alumni_list' %}">Alumni Hall of Fame</a></li>
        <li><a href="#">Exhibition</a></li>
    </ul>
    <ul class="dropdown-content" id="campus">
        <li><a href="#">Facilities</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">Extra-Curricular</a></li>
    </ul>
    <ul class="dropdown-content" id="mss">
      <li><a href="{% url 'anonymous:report' %}">Anonymous Reporting</a></li>
      <li><a href="{% url 'blog:post_new' %}">Make a Blog Post</a></li>
      <li><a href="{% url 'evoting:polllist' %}">E-voting</a></li>
      <li><a href="{% url 'counselor:chat' 'counselor' %}">Counselor Chat</a></li>
    </ul>
    <!-- Mobile Dropdowns -->
    <ul class="dropdown-content" id="schools-m">
      <li><a href="#">Nursery School<z/a></li>
      <li><a href="#">Primary School</a></li>
      <li><a href="#">Secondary School</a></li>
  </ul>
  <ul class="dropdown-content" id="home-m">
      <li><a href="#">About Us</a></li>
      <li><a href="#">History</a></li>
  </ul>
  <ul class="dropdown-content" id="student-m">
    <li><a href="{% url 'awards:awards' %}">Awards</a></li>
    <li><a href="{% url  'blog:list_post' %}">Blog</a></li>
    <li><a href="{% url 'alumni:alumni_list' %}">Alumni Hall of Fame</a></li>
    <li><a href="#">Exhibition</a></li>
  </ul>
  <ul class="dropdown-content" id="campus-m">
      <li><a href="#">Facilities</a></li>
      <li><a href="#">News</a></li>
      <li><a href="#">Extra-Curricular</a></li>
  </ul>
  <ul class="dropdown-content" id="mss-m">
    <li><a href="{% url 'anonymous:report' %}">Anonymous Reporting</a></li>
    <li><a href="{% url 'blog:post_new' %}">Make a Blog Post</a></li>
    <li><a href="{% url 'evoting:polllist' %}">E-voting</a></li>
    <li><a href="{% url 'counselor:chat' 'counselor' %}">Counselor Chat</a></li>
  </ul>

  </nav>
  <ul id="genre-dropdown" class="dropdown-content center">
      <li><a href="#" class="teal">Tech</a></li>
      <li><a href="#" class="teal">Health</a></li>
      <li><a href="#" class="teal">Education</a></li>
      <li><a href="#" class="teal">Others</a></li>
  </ul>
    {% block content %}
    {% endblock %}
    <!--Import jQuery before materialize.js-->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/test.js' %}"></script>
  <script>
    $(document).ready(function () {
      $('.dropdown-button').dropdown({
        constrainWidth: false,
        hover: true,
        belowOrigin: true,
        alignment: 'left'
      });

      // JAVASCRIPT START HERE //
      $('.button-collapse').sideNav()
      $('select').material_select()
      
    });
  </script>
</body>
</html>